# **Complete EDA On Google Playstore Apps**

## About Dataset

This is google playstore apps dataset available at [Kaggle](https://www.kaggle.com/lava18/google-play-store-apps)


`Context`

While many public datasets (on Kaggle and the like) provide Apple App Store data, there are not many counterpart datasets available for Google Play Store apps anywhere on the web. On digging deeper, I found out that iTunes App Store page deploys a nicely indexed appendix-like structure to allow for simple and easy web scraping. On the other hand, Google Play Store uses sophisticated modern-day techniques (like dynamic page load) using JQuery making scraping more challenging.

`Content`
Each app (row) has values for catergory, rating, size, and more.

`Acknowledgements`

This information is scraped from the Google Play Store. This app information would not be available without it.

`Inspiration`

The Play Store apps data has enormous potential to drive app-making businesses to success. Actionable insights can be drawn for developers to work on and capture the Android market!

## 1. Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

import matplotlib.pyplot as plt
%matplotlib inline

**ignore warnings**

In [2]:
import warnings
warnings.filterwarnings("ignore")

## 2.0 Data Loading, Filtering And Cleaning

. Load the csv file with the pandas

. creating the dataframe and understanding the data present in the dataset using pandas

. Dealing with the missing data, outliers and the incorrect records

In [3]:
df = pd.read_csv(r"D:\OneDrive\Desktop\data-analysis-course-preply\lectures\lecture-03-Google-Playstore-EDA\googleplaystore.csv")

In [4]:
df.head()

,a,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Unnamed: 13
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,NaN
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,NaN
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,NaN
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,NaN
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,NaN

checking columns in the dataset

In [5]:
df.columns

Index(['a', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver', 'Unnamed: 13'],
      dtype='str')

### checking number of rows and columns

In [6]:
df.shape

(10841, 14)

### checking what kind of data types we have in the dataset

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   a               10841 non-null  str
 1   Category        10840 non-null  str
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  int64
 4   Size            10841 non-null  str
 5   Installs        10841 non-null  str
 6   Type            10840 non-null  str
 7   Price           10841 non-null  str
 8   Content Rating  10841 non-null  str
 9   Genres          10840 non-null  str
 10  Last Updated    10841 non-null  str
 11  Current Ver     10833 non-null  str
 12  Android Ver     10839 non-null  str
 13  Unnamed: 13     0 non-null      float64
dtypes: float64(2), int64(1), str(11)
memory usage: 1.2 MB

In [9]:
df.describe()

            Rating       Reviews  Unnamed: 13
count  9367.000000  1.084100e+04          0.0
mean      4.191513  4.441119e+05          NaN
std       0.515735  2.927629e+06          NaN
min       1.000000  0.000000e+00          NaN
25%       4.000000  3.800000e+01          NaN
50%       4.300000  2.094000e+03          NaN
75%       4.500000  5.476800e+04          NaN
max       5.000000  7.815831e+07          NaN

## Observation 1

-> We have 10841 and 13 columns in the dataset

-> We have columns of different data types

-> The columns in the dataset are: 

`'a', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver', 'Unnamed: 13'`

-> There are some missing values in the dataset, we'll handle them latter

-> There are some columns present which should be numeric but are not numeric

`Size` , `Price` , `Installs`

### **Converting Size Column To Numeric**

In [10]:
# check if size column has null values or not
df['Size'].isnull().sum()

np.int64(0)

we don't have null values, we are good to go

In [12]:
pd.set_option('display.max_columns', None) # this is to display all the columns in the dataframe
pd.set_option('display.max_rows', None) # this is to display all the rows in the dataframe

In [23]:
# checking unique values inside Size columns
df['Size'].unique()

array([1.99229440e+07, 1.46800640e+07, 9.12261120e+06, 2.62144000e+07,
       2.93601280e+06, 5.87202560e+06, 3.04087040e+07, 3.46030080e+07,
       3.25058560e+06, 2.93601280e+07, 1.25829120e+07, 2.09715200e+07,
       2.20200960e+07, 3.87973120e+07, 2.83115520e+06, 5.76716800e+06,
       1.78257920e+07, 4.08944640e+07, 3.25058560e+07, 4.40401920e+06,
       7.34003200e+06, 2.41172480e+07, 6.29145600e+06, 6.39631360e+06,
       4.82344960e+06, 9.64689920e+06, 5.45259520e+06, 1.15343360e+07,
       2.51658240e+07,            nan, 9.85661440e+06, 1.57286400e+07,
       1.04857600e+07, 1.25829120e+06, 2.72629760e+07, 8.38860800e+06,
       8.28375040e+06, 5.87202560e+07, 5.97688320e+07, 3.67001600e+07,
       5.66231040e+07, 2.05824000e+05, 3.77487360e+06, 5.97688320e+06,
       9.01775360e+06, 2.51658240e+06, 2.83115520e+07, 2.62144000e+06,
       1.67772160e+07, 3.56515840e+06, 9.33232640e+06, 4.08944640e+06,
       3.04087040e+06, 3.98458880e+07, 3.35544320e+07, 5.66231040e+06,
       1.88743680e+07, 1.15343360e+06, 2.30686720e+06, 4.71859200e+06,
       1.02760448e+07, 5.45259520e+07, 9.43718400e+06, 7.02545920e+06,
       3.14572800e+07, 2.72629760e+06, 7.44488960e+06, 3.87973120e+06,
       2.30686720e+07, 7.75946240e+06, 6.71088640e+06, 3.35544320e+06,
       8.59832320e+06, 1.03809024e+07, 5.13802240e+06, 9.96147200e+06,
       5.24288000e+06, 6.18659840e+06, 1.36314880e+07, 7.65460480e+07,
       7.13031680e+06, 3.67001600e+06, 4.19430400e+06, 2.41172480e+06,
       7.54974720e+06, 2.20200960e+06, 4.40401920e+07, 7.65460480e+06,
       9.54204160e+06, 5.76716800e+07, 2.35520000e+04, 6.81574400e+06,
       1.57286400e+06, 7.86432000e+06, 5.34773760e+07, 4.29916160e+07,
       5.03316480e+07, 8.91289600e+06, 4.82344960e+07, 8.70318080e+06,
       4.50887680e+06, 4.92830720e+06, 3.46030080e+06, 4.19430400e+07,
       8.17889280e+06, 9.22746880e+06, 6.92060160e+06, 5.34773760e+06,
       6.39631360e+07, 6.92060160e+07, 8.08960000e+04, 8.80803840e+06,
       1.20832000e+05, 4.61373440e+07, 7.11680000e+05, 1.67772160e+06,
       6.50117120e+06, 1.84320000e+04, 5.55745280e+07, 1.46800640e+06,
       3.14572800e+06, 6.08174080e+06, 3.98458880e+06, 1.00663296e+07,
       4.71859200e+07, 6.60602880e+07, 5.13802240e+07, 8.07403520e+07,
       4.61373440e+06, 5.03316480e+06, 7.34003200e+07, 7.23517440e+06,
       9.75175680e+06, 8.49346560e+06, 3.77487360e+07, 8.80803840e+07,
       1.01711872e+08, 2.09715200e+06, 1.99229440e+06, 1.88743680e+06,
       5.55745280e+06, 4.92830720e+07, 5.69344000e+05, 5.38624000e+05,
       7.96917760e+07, 7.96917760e+06, 6.18659840e+07, 1.01711872e+07,
       8.17889280e+07, 7.54974720e+07, 4.50887680e+07, 8.07403520e+06,
       6.60602880e+06, 3.42016000e+05, 3.56515840e+07, 9.75175680e+07,
       6.81574400e+07, 8.28375040e+07, 1.04857600e+08, 6.08174080e+07,
       5.24288000e+07, 7.13031680e+07, 6.71088640e+07, 7.02545920e+07,
       6.29145600e+07, 9.85661440e+07, 2.37568000e+05, 1.03809024e+08,
       6.38976000e+05, 9.96147200e+07, 8.70400000e+03, 4.19840000e+04,
       2.99008000e+05, 1.12640000e+04, 8.38860800e+07, 1.78257920e+06,
       7.75946240e+07, 6.50117120e+07, 7.23517440e+07, 7.86432000e+07,
       1.02760448e+08, 8.91289600e+07, 8.59832320e+07, 1.00663296e+08,
       9.12261120e+07, 7.44488960e+07, 9.01775360e+07, 9.54204160e+07,
       8.49346560e+07, 9.64689920e+07, 8.70318080e+07, 9.22746880e+07,
       7.20896000e+05, 8.82688000e+05, 9.20576000e+05, 3.87072000e+05,
       2.72384000e+05, 3.84000000e+05, 1.36314880e+06, 9.98400000e+05,
       1.00352000e+06, 4.29916160e+06, 9.33232640e+07, 7.12704000e+05,
       5.57056000e+05, 5.37600000e+05, 9.42080000e+05, 7.97696000e+05,
       8.73472000e+05, 7.37280000e+05, 7.30112000e+05, 7.90528000e+05,
       3.25632000e+05, 5.93920000e+04, 2.46784000e+05, 2.00704000e+05,
       8.77568000e+05, 5.22240000e+04, 9.75872000e+05, 8.85760000e+05,
       2.57024000e+05, 9.52320000e+05, 5.52960000e+05, 3.20512000e+05,
       7.63904000e+05, 2.07872000e+05, 2.66240000e+04, 3.21536000e+05,
       2.44736000e+05, 3.79904000e+05, 2.25280000e+05, 7.47520000e+05,
       7.74144000e+05, 9.31840000e+04, 3.00032000e+05, 1.74080000e+04,
       7.57760000e+04, 1.43360000e+04, 3.24608000e+05, 7.98720000e+04,
       9.46176000e+05, 9.23648000e+05, 8.37632000e+05, 8.29440000e+04,
       9.61536000e+05, 1.73056000e+05, 4.60800000e+04, 4.86400000e+05,
       9.88160000e+05, 9.43718400e+07, 5.58080000e+05, 6.24640000e+04,
       2.89792000e+05, 6.70720000e+05, 7.31136000e+05, 9.52320000e+04,
       8.92928000e+05, 1.23904000e+05, 3.29728000e+05, 1.04857600e+06,
       9.99424000e+05, 1.76128000e+05, 2.43712000e+05, 5.62176000e+05,
       2.10944000e+05, 9.76896000e+05, 4.54656000e+05, 7.34208000e+05,
       2.15040000e+05, 6.23616000e+05, 3.15392000e+05, 7.21920000e+05,
       3.13344000e+05, 9.25696000e+05, 4.84352000e+05, 1.79200000e+05,
       3.58400000e+05, 3.92192000e+05, 4.64896000e+05, 4.31104000e+05,
       7.16800000e+04, 8.31488000e+05, 4.52608000e+05, 8.62208000e+05,
       4.27008000e+05, 4.21888000e+05, 4.70016000e+05, 4.89472000e+05,
       3.43040000e+05, 8.00768000e+05, 7.38304000e+05, 4.40320000e+05,
       4.39296000e+05, 1.96608000e+05, 2.04800000e+05, 4.71040000e+05,
       7.45472000e+05, 5.07904000e+05, 8.35584000e+05, 4.23936000e+05,
       5.18144000e+05, 9.08288000e+05, 6.27712000e+05, 2.48832000e+05,
       5.82656000e+05, 7.96672000e+05, 6.99392000e+05, 6.06208000e+05,
       3.26656000e+05, 1.90464000e+05, 8.60160000e+05, 6.62528000e+05,
       1.95584000e+05, 3.81952000e+05, 4.47488000e+05, 6.12352000e+05,
       7.33184000e+05, 5.99040000e+05, 1.00556800e+06, 2.27328000e+05,
       2.24256000e+05, 5.63200000e+04, 9.70752000e+05, 3.30752000e+05,
       7.07584000e+05, 5.23264000e+05, 9.73824000e+05, 9.86112000e+05,
       2.56000000e+04, 5.67296000e+05, 3.59424000e+05, 2.76480000e+04,
       8.39680000e+04, 2.12992000e+05, 9.34912000e+05, 5.26336000e+05,
       5.64224000e+05, 2.96960000e+04, 1.05472000e+05, 9.19552000e+05,
       7.60832000e+05, 1.18784000e+05, 1.56672000e+05, 2.14016000e+05,
       3.61472000e+05, 5.10976000e+05, 1.77152000e+05, 6.11328000e+05,
       8.28416000e+05, 1.24928000e+05, 4.20864000e+05, 4.09600000e+05,
       8.20224000e+05, 8.05888000e+05, 2.42688000e+05, 5.12000000e+04,
       6.58432000e+05, 1.00966400e+06, 9.93280000e+04, 5.28384000e+05,
       8.57088000e+05, 7.98720000e+05, 9.84064000e+05, 2.75456000e+05,
       2.04800000e+04, 5.09952000e+05, 6.14400000e+05, 7.66976000e+05,
       6.57408000e+05, 9.02144000e+05, 7.37280000e+04, 6.71744000e+05,
       6.15424000e+05, 2.26304000e+05, 2.33472000e+05, 1.10592000e+05,
       9.62560000e+05, 1.80224000e+05, 3.37920000e+04, 6.78912000e+05,
       3.48160000e+04, 9.64608000e+05, 2.65216000e+05, 1.67936000e+05,
       4.68992000e+05, 2.50880000e+05, 6.44096000e+05, 2.86720000e+04,
       2.94912000e+05, 7.93600000e+05, 8.03840000e+05, 6.51264000e+05,
       9.37984000e+05, 1.01785600e+06, 3.16416000e+05, 4.96640000e+05,
       9.35936000e+05, 9.24672000e+05, 6.22592000e+05, 5.12000000e+05,
       5.52960000e+04, 5.75488000e+05, 8.67328000e+05, 9.79968000e+05,
       7.04512000e+05, 8.30464000e+05, 2.76480000e+05, 4.91520000e+04,
       3.36896000e+05, 5.35552000e+05, 9.43104000e+05, 8.94976000e+05,
       1.00454400e+06, 8.02816000e+05, 2.86720000e+05, 2.45760000e+04,
       5.30432000e+05, 7.72096000e+05, 9.13408000e+05, 1.57696000e+05,
       8.80640000e+05, 3.72736000e+05, 3.96288000e+05, 6.41024000e+05,
       1.64864000e+05, 9.00096000e+05, 3.99360000e+04, 9.93280000e+05,
       1.74080000e+05, 1.44384000e+05, 1.63840000e+05, 1.47456000e+05,
       1.46432000e+05, 1.94560000e+05, 3.85024000e+05, 1.97632000e+05,
       2.51904000e+05, 7.47520000e+04, 6.73792000e+05, 1.01580800e+06,
       2.59072000e+05, 4.30080000e+05, 4.13696000e+05, 4.81280000e+05,
       2.31424000e+05, 2.45760000e+05, 9.11360000e+04, 2.39616000e+05,
       2.63168000e+05, 8.81664000e+05, 4.78208000e+05, 1.60768000e+05,
       4.50560000e+04, 6.92224000e+05, 6.86080000e+04, 5.65248000e+05,
       9.06240000e+05, 1.04448000e+06, 5.95968000e+05, 6.33856000e+05])

In [ ]:
# find the values inside Size column that has 'M' in it
df['Size'].loc[df['Size'].str.contains('M')].value_counts().sum()

np.int64(8830)

In [17]:
# find the values inside Size column that has 'K' in it
df['Size'].loc[df['Size'].str.contains('k')].value_counts().sum()

np.int64(316)

In [19]:
# find the values inside Size column that has Varies with device in it
df['Size'].loc[df['Size'].str.contains('Varies with device')].value_counts().sum()

np.int64(1695)

In [20]:
# Total values inside size column
df['Size'].value_counts().sum()

np.int64(10841)

## Observation 2

`We have 8830 values in M units`

`We have 316 values in k units`

`We have 1695 value in Varies with device`

In [ ]:
# step 1: WE will  covert 'M'=  10^6 and K = 10^3 into bytes and varies with device as well 
# And then convert them into numeric

def convert_size(size):
    
    if isinstance(size, str): #isinstance(object, type)  -> True, if the object is of that type
        
        if 'k' in size:   # chcek if size is a string like size = '19M' And then isinstance(size, str) returns True
            return float(size.replace('k', '')) * 1024
        # size.replace -> 
        elif 'M' in size:
            return float(size.replace('M', '')) * 1024 * 1024
        elif 'Varies with device' in size:
            return np.nan  #NUMPY
    return size

df['Size'] = df['Size'].apply(convert_size)

In [24]:
# rename the column name 'Size' to 'Size_in_bytes'
df.rename(columns={'Size': 'Size_in_bytes'}, inplace=True)

In [ ]:
# making a new column called 'Size in Mb' which will have the size in MB

df['Size_in_Mb'] = df['Size_in_bytes'].apply(lambda x: x/(1024*1024))

## Assignment: Get idea about Lamda Function
## You will deal with Install Column and Convert String values to numeric